### ISSUE TITLE
Spectrum is broken when starting OBS

### ISSUE THREAD

**Issue by NxRoot** [univrsal/spectralizer#47] opened 2021-01-22 18:25 UTC
Every time I open OBS I need to open the spectralizer component and fix the 'Detail' field.
i dont want to be doing this every time i enter obs. Footage on below link.

[VIDEO](https://streamable.com/ie9ju2)

Image:
![Image Of Bug fixing](https://i.ibb.co/y0V2Wfy/Untitled.png)

**Comment by univrsal** [comment] 2021-01-22 18:55
I need the obs studio log and a screenshot of the entire properties for the source

**Comment by univrsal** [comment] 2021-11-28 13:46
Most likely a duplicate of #38

**Closed as completed by univrsal** 2021-11-28 13:46 UTC
