### ISSUE TITLE
OBS Crashes on startup 

### ISSUE THREAD

**Issue by PlayeyWAWN** [univrsal/spectralizer#55] opened 2021-09-17 07:58 UTC
The plugin is just awesome, I really love it but after installing and using it for 2 days it just keeps on crashing on the scene collection that I'm using it for. I had to uninstall it for me to get back to streaming otherwise I just can't open OBS. Crash logs are attached lemme know if this can be fixed (hopefull
[Crash 2021-09-17 15-38-05.txt](https://github.com/univrsal/spectralizer/files/7183768/Crash.2021-09-17.15-38-05.txt)
[Crash 2021-09-17 15-38-36.txt](https://github.com/univrsal/spectralizer/files/7183770/Crash.2021-09-17.15-38-36.txt)
[Crash 2021-09-17 15-40-22.txt](https://github.com/univrsal/spectralizer/files/7183771/Crash.2021-09-17.15-40-22.txt)
y)

**Comment by univrsal** [comment] 2021-09-17 10:06
The crashlogs contain no useful information so there's not much I can do. Also it's most likely a duplicate of #50

**Closed as completed by univrsal** 2021-09-17 10:06 UTC
