### ISSUE TITLE
It will freeze the bars on the Vlc when on studio mode.

### ISSUE THREAD

**Issue by iesv** [univrsal/spectralizer#61] opened 2021-11-28 13:32 UTC
System: win10 x64 1809
OBS: 27.1.3
Display card: RX580

At first:
1. Open OBS
1. Click "stereo"
2. Transition
3. It will freeze the bars in the **program** when on **studio mode**.
![image](https://user-images.githubusercontent.com/16969250/143770080-227d0876-5c2b-460c-a037-09a1fddacbca.png)

On the other hand:
1. Exit OBS
2. Open  OBS
3. It will freeze the bars in the **Preview** when on **studio mode**.
And then sometimes are normal and sometimes are innormal after many exits and opening obs.

**Comment by univrsal** [comment] 2021-11-28 13:47
Most likely a duplicate of #38

**Closed as completed by univrsal** 2021-11-28 13:47 UTC

**Comment by iesv** [comment] 2021-11-29 02:22
Oh, It only seems to have this problem on 1.3.4 version, but the 1.3.2 is normal.
